from __future__ import annotations

from dataclasses import dataclass
import hashlib

from pyxis.rir.model import RepositoryIR


@dataclass(frozen=True, slots=True)
class GeneratedArtifact:
    """One deterministic compiler product derived from the RIR."""

    path: str
    source: str
    node_sha256: str


def _node_hash(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def compile_inspect_text(repository: RepositoryIR) -> GeneratedArtifact:
    """Compile the first permanent capability artifact.

    This function consumes only the RIR. It neither reads canonical authoring
    state nor executes generated behavior.
    """

    if "inspect_text" not in repository.workspace.capabilities:
        raise ValueError("RIR does not reference inspect_text.")

    node_identity = "|".join(
        (
            repository.schema_version,
            repository.repository_id,
            repository.workspace.workspace_id,
            "inspect_text",
            "builtin.inspect_text.v1",
        )
    )
    node_sha256 = _node_hash(node_identity)

    source = (
        "# Generated by Pyxis\n"
        f"# Node-SHA256: {node_sha256}\n\n"
        "import hashlib\n\n"
        "def execute(text: str) -> dict[str, object]:\n"
        "    return {\n"
        "        \"characters\": len(text),\n"
        "        \"words\": len(text.split()),\n"
        "        \"sha256\": hashlib.sha256(text.encode(\"utf-8\")).hexdigest(),\n"
        "    }\n"
    )

    return GeneratedArtifact(
        path="generated/capabilities/inspect_text.py",
        source=source,
        node_sha256=node_sha256,
    )
