from __future__ import annotations

from dataclasses import dataclass
import hashlib

from pyxis.rir.model import RepositoryIR


@dataclass(frozen=True, slots=True)
class GeneratedArtifact:
    """One deterministic compiler product derived from the RIR."""

    path: str
    source: str
    node_sha256: str


def _node_hash(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _capability_node_identity(
    repository: RepositoryIR,
    capability_id: str,
    generator_id: str,
) -> str:
    return "|".join(
        (
            repository.schema_version,
            repository.repository_id,
            repository.workspace.workspace_id,
            capability_id,
            generator_id,
        )
    )


def _workspace_node_identity(
    repository: RepositoryIR,
    generator_id: str,
) -> str:
    """Return the deterministic identity of the composed Workspace node."""

    return "|".join(
        (
            repository.schema_version,
            repository.repository_id,
            repository.workspace.workspace_id,
            repository.workspace.entrypoint,
            *repository.workspace.capabilities,
            generator_id,
        )
    )


def compile_inspect_text(repository: RepositoryIR) -> GeneratedArtifact:
    """Compile the deterministic inspect_text capability artifact."""

    if "inspect_text" not in repository.workspace.capabilities:
        raise ValueError("RIR does not reference inspect_text.")

    node_sha256 = _node_hash(
        _capability_node_identity(
            repository,
            "inspect_text",
            "builtin.inspect_text.v1",
        )
    )

    source = (
        "# Generated by Pyxis\n"
        f"# Node-SHA256: {node_sha256}\n\n"
        "import hashlib\n\n"
        "def execute(text: str) -> dict[str, object]:\n"
        "    return {\n"
        "        \"characters\": len(text),\n"
        "        \"words\": len(text.split()),\n"
        "        \"sha256\": hashlib.sha256(text.encode(\"utf-8\")).hexdigest(),\n"
        "    }\n"
    )

    return GeneratedArtifact(
        path="generated/capabilities/inspect_text.py",
        source=source,
        node_sha256=node_sha256,
    )


def compile_normalize_text(repository: RepositoryIR) -> GeneratedArtifact:
    """Compile the deterministic normalize_text capability artifact.

    Like every capability compiler, this consumes only the RIR and emits source
    without executing it or reading canonical authoring state.
    """

    if "normalize_text" not in repository.workspace.capabilities:
        raise ValueError("RIR does not reference normalize_text.")

    node_sha256 = _node_hash(
        _capability_node_identity(
            repository,
            "normalize_text",
            "builtin.normalize_text.v1",
        )
    )

    source = (
        "# Generated by Pyxis\n"
        f"# Node-SHA256: {node_sha256}\n\n"
        "def execute(text: str) -> dict[str, object]:\n"
        "    normalized = \" \".join(text.split())\n"
        "    return {\n"
        "        \"normalized_text\": normalized,\n"
        "        \"changed\": normalized != text,\n"
        "    }\n"
    )

    return GeneratedArtifact(
        path="generated/capabilities/normalize_text.py",
        source=source,
        node_sha256=node_sha256,
    )


def compile_split_lines(repository: RepositoryIR) -> GeneratedArtifact:
    """Compile the deterministic split_lines capability artifact."""

    if "split_lines" not in repository.workspace.capabilities:
        raise ValueError("RIR does not reference split_lines.")

    node_sha256 = _node_hash(
        _capability_node_identity(
            repository,
            "split_lines",
            "builtin.split_lines.v1",
        )
    )

    source = (
        "# Generated by Pyxis\n"
        f"# Node-SHA256: {node_sha256}\n\n"
        "def execute(text: str) -> dict[str, object]:\n"
        "    lines = text.splitlines()\n"
        "    return {\n"
        "        \"lines\": lines,\n"
        "        \"line_count\": len(lines),\n"
        "    }\n"
    )

    return GeneratedArtifact(
        path="generated/capabilities/split_lines.py",
        source=source,
        node_sha256=node_sha256,
    )


def compile_workspace_entrypoint(repository: RepositoryIR) -> GeneratedArtifact:
    """Compose referenced capability artifacts into one Workspace entrypoint.

    Composition remains a pure compiler operation: it consumes only the RIR and
    emits deterministic source. It does not write files, import generated code,
    or execute the Workspace.
    """

    node_sha256 = _node_hash(
        _workspace_node_identity(
            repository,
            "builtin.workspace_python.v1",
        )
    )

    imports = "\n".join(
        f"from capabilities.{capability_id} import execute as execute_{capability_id}"
        for capability_id in repository.workspace.capabilities
    )
    calls = "\n".join(
        f'        "{capability_id}": execute_{capability_id}(text),'
        for capability_id in repository.workspace.capabilities
    )

    source = (
        "# Generated by Pyxis\n"
        f"# Node-SHA256: {node_sha256}\n\n"
        f"{imports}\n\n"
        "def run_text(text: str) -> dict[str, object]:\n"
        "    return {\n"
        f"{calls}\n"
        "    }\n"
    )

    return GeneratedArtifact(
        path=(
            "generated/workspaces/"
            f"{repository.workspace.workspace_id}/"
            f"{repository.workspace.entrypoint}"
        ),
        source=source,
        node_sha256=node_sha256,
    )
